---
development:
  cloud_name: hd56k2h70
  api_key: '527147573139898'
  api_secret: oqm0W4qugvoGeaZQK3SixGYfWFY
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: hd56k2h70
  api_key: '527147573139898'
  api_secret: oqm0W4qugvoGeaZQK3SixGYfWFY
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: hd56k2h70
  api_key: '527147573139898'
  api_secret: oqm0W4qugvoGeaZQK3SixGYfWFY
  enhance_image_tag: true
  static_file_support: false
